spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(36MN2ZfvS/QLkIEMj9NxZtc02n2SP+ZG+9FRqPFjctO2C39tc6dXqrtmy6DX4FLYIcu+n9EdcJ9Hg2byHlv1xmfS1yYSWlSLbYaBMR0tHSSaxNQBPHpP7YAuy9HzgXyfN2ifkfBPh/k=)
    username: ENC(i8MqHziWKlHbuA5lcbKNOQ==)
    password: ENC(RFz+SpSt3NqT8zX02nq4XDCendNAqxiC)
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

springdoc:
  version: v1.0.0
  swagger-ui:
    path: /swagger-agebloomers.html
    tagsSorter: alpha
    operationsSorter: alpha

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: authorization,content-type,x-auth-token
  max-age: 3600